#!/bin/sh

# Enable debugging on highest log level
if [ x"${BUILD_LOG_LEVEL}" = 5 ]; then
  set -x
fi

# ==============================================================================

# Global STI variable setup
source `dirname "$0"`/sti-setup

# Maven arguments setting up the environment
maven_env_args="-Dmaven.repo.local=${STI_ARTIFACTS_DIR}/m2"

# =========================================================================
# Helper functions:

function check_error() {
  local label=$1
  local error=$2
  if [ ${error} -ne 0 ]; then
    echo "Aborting due to error code $error for $label"
    exit ${error}
  fi
}


function get_output_dir() {
  # Where artifacts are created within the build
  local dir=${OUTPUT_DIR:-${STI_SOURCE_DIR}/target}
  # If output_dir is not absolute then use it relative to STI_SOURCE_DIR
  if [ "${dir:0:1}" != "/" ]; then
     dir="${STI_SOURCE_DIR}/${dir}"
  fi
  echo ${dir}
}


function copy_dir() {
  local src=$1
  local dest=$2

  cp -r ${src}/* ${dest}
  check_error "copying ${src} to ${dest}" $?
}

function mvn_settings_with_mirror {
  cat <<EOT
<settings>
  <mirrors>
    <mirror>
      <id>sti-mirror</id>
      <url>$1</url>
      <mirrorOf>central</mirrorOf>
    </mirror>
  </mirrors>
</settings>
EOT
}

function setup_maven() {
  if [ x"${MAVEN_MIRROR_URL}" != x ]; then
    echo "`mvn_settings_with_mirror ${MAVEN_MIRROR_URL}`" > ${STI_SOURCE_DIR}/mvn-mirrors-settings.xml
    maven_env_args="${maven_env_args} -s ${STI_SOURCE_DIR}/mvn-mirrors-settings.xml"
  elif [ -f "${STI_SOURCE_DIR}/.m2/settings.xml" ]; then
    maven_env_args="${maven_env_args} -s ${STI_SOURCE_DIR}/.m2/settings.xml"
  fi
}

function build_maven() {
  # Where artefacts are created during build
  local output_dir=$1

  # Where to put the artefacts
  local app_dir=$2

  # Default args: no tests
  local hawt_app_args="io.fabric8:hawt-app-maven-plugin:2.2.45:build";
  if [ x"${JAVA_MAIN_CLASS}" != x ]; then
    hawt_app_args="-Dhawt-app.main=${JAVA_MAIN_CLASS} ${hawt_app_args}"
  fi

  local maven_args="${MAVEN_ARGS:-package ${hawt_app_args} -DskipTests -e}"
  local maven_dep_args=""

  # If module is specified, only build this module
  if [ x"$MAVEN_MODULE" != x ]; then
    maven_args="${maven_args} -pl $MAVEN_MODULE -am"
    maven_dep_args="-pl $MAVEN_MODULE -am"
  fi

  echo "Found pom.xml ... attempting to build with mvn ${maven_args}"

  local old=$(pwd)
  cd ${STI_SOURCE_DIR}
  check_error "changing directory to ${STI_SOURCE_DIR}" $?

  # =========
  # Run Maven
  mvn --version
  mvn ${maven_env_args} ${maven_args} ${MAVEN_EXTRA_ARGS}
  check_error "Maven build" $?

  # ==============
  # Copy artefacts
  echo "Copying Maven artifacts from ${output_dir} to ${app_dir} ..."
  copy_dir ${output_dir} ${app_dir}

  # cleanup maven build artifacts to reduce image size
  echo "Cleaning up maven build artifacts using mvn clean..."
  mvn clean

  if [ "x${MAVEN_CLEAR_REPO}" != "x" ]; then
    rm -rf "${STI_ARTIFACTS_DIR}/m2"
    check_error "Cannot remove local Maven repository ${STI_ARTIFACTS_DIR}/m2" $?
  fi

  cd $old
}

# =========================================================================
# Main

if [ -f "${STI_SOURCE_DIR}/pom.xml" ]; then
  # If a pom.xml is present use maven
  setup_maven
  build_maven $(get_output_dir) ${DEPLOYMENTS_DIR}
else
  # Assuming that the source already contains compiled artefacts
  echo "Copying binaries from ${output_dir} to ${STI_ARTIFACTS_DIR} ..."
  copy_dir $(get_output_dir) ${DEPLOYMENTS_DIR}
fi

echo "... done"
