#!/bin/sh

# ==============================================================================
# Variable setup

. sti-setup

# Where artifacts are created within the build
output_dir=${OUTPUT_DIR:-${sti_source_dir}/target}
if [ "${output_dir:0:1}" != "/" ]; then
   output_dir="${sti_source_dir}/${output_dir}"
fi

# Directory where to deploy generated artifacts
app_dir=${JAVA_APP_DIR:-/app}
[ -d ${app_dir} ] || mkdir -p ${app_dir}

# =========================================================================
# Helper functions:

function check_error() {
  label=$1
  error=$2
  if [ $error -ne 0 ]; then
    echo "Aborting due to error code $error from $label"
    exit $error
  fi
}

function build_maven() {

  # Read in any properties set during the build. Copy it over to setenv.sh used in run-java.sh
  [ -f "${app_dir}/setenv.sh" ] && rm "${app_dir}/setenv.sh"
  for sti_env in "${output_dir}/sti.env" "${output_dir}/classes/sti.env"; do
     if [ -f "${sti_env}" ]; then
        . ${sti_env}
        cat ${sti_env} >> "${app_dir}/setenv.sh"
     fi
  done

  # Default args: no tests
  maven_args=${MAVEN_ARGS:-package -DskipTests -e}
  maven_dep_args=""

  if [ x"$MAVEN_MODULE" != x ]; then
    maven_args="${maven_args} -pl $MAVEN_MODULE -am"
    maven_dep_args="-pl $MAVEN_MODULE -am"
  fi
  echo "Found pom.xml ... attempting to build with mvn ${maven_args}"

  old=$(pwd)
  cd ${sti_source_dir}

  # Run Maven
  mvn --version
  mvn -Dmaven.repo.local=${sti_artifacts_dir}/m2 ${maven_args} ${MAVEN_EXTRA_ARGS}

  check_error "Maven build" $?

  # Write out dependencies into a dedicated file
  mvn -Dmaven.repo.local=${sti_artifacts_dir}/m2 \
      -Dmdep.outputFile=${output_dir}/classpath \
      ${maven_dep_args} ${MAVEN_DEP_CLASSPATH_OPTS} \
      dependency:build-classpath

  echo "Copying Maven artefacts from ${output_dir} to ${app_dir} ..."
  cp -r ${output_dir}/* ${app_dir} >& /dev/null

  cd $old
}

function plain_copy() {
  # Assuming that the source already contains compiled artefacts
  echo "Copying binaries from ${output_dir} to ${app_dir} ..."
  cp -r ${output_dir}/* ${app_dir} >& /dev/null
}

# =========================================================================
if [ -f "${sti_source_dir}/pom.xml" ]; then
  # If a pom.xml is present use maven
  build_maven
else
  plain_copy
fi

echo "... done"
